version: 2.1
description: Using IPSec VPN connectivity from Ubuntu, manage deployment thru tunnel.

jobs:
  remote-deploy:
    parameters:
      deploy-script:
        description: path to executable file for deployment
        type: string
        default: /tmp/deploy_script.sh
    executor: machine-ubuntu
    steps:
      - attach_workspace:
          at: /tmp
      - deploy-docker-vpn:
          deploy-script: <<parameters.deploy-script>>

commands:
  deploy-docker-vpn:
    parameters:
      deploy-script:
        type: string
    description: Install & configure IPSec VPN
    steps:
      - run:
          name: ORB IPSec - Finalize deploy script
          command: |
            echo -e "#!/bin/bash\n/usr/bin/wg-quick up tunnel\n$(cat <<parameters.deploy-script>>)" \
              > <<parameters.deploy-script>>
      - run:
          name: ORB IPSec - Setup VPNC IPSec tunnel inside docker container
          command: |
            docker login -u $CTX_DOCKER_USER -p $CTX_DOCKER_PASS
            if docker pull danackerson/vpn_deploy:$IPSEC_IMG_VERSION; then
              echo "Using existing $IPSEC_IMG_VERSION for deploy..."
            else
            cat \<<EOF >tunnel.conf
            [Interface]
            PrivateKey = "$CTX_WG_CIRCLECI_PRIVATE_KEY"
            Address = 10.0.0.3/24

            [Peer]
            PublicKey = "$CTX_WG_SERVER_PUBLIC_KEY"
            PresharedKey = "$CTX_WG_CIRCLECI_PRESHARED_KEY"
            AllowedIPs = 10.0.0.3/32, 192.168.178.0/24
            Endpoint = "$CTX_WG_SERVER_ENDPOINT"
            EOF

            curl -O https://raw.githubusercontent.com/danackerson/circleci-orb-ipsec/wg/Dockerfile
            # build docker image which will create the IPSec tunnel
            docker build . \
              --build-arg DEPLOY_SCRIPT_FILENAME=<<parameters.deploy-script>> \
              --build-arg SERVER_DEPLOY_KEY=$CTX_SERVER_DEPLOY_SECRET -t danackerson/vpn_deploy:$IPSEC_IMG_VERSION

            docker push danackerson/vpn_deploy:$IPSEC_IMG_VERSION
            fi
      - run:
          name: ORB IPSec - notify bender slackbot of VPN connection
          command: |
            curl -s -X POST \
            "https://slack.com/api/chat.postMessage?token=$CTX_SLACK_API_TOKEN&channel=$CTX_SLACK_CHANNEL&text=%3Acircleci%3A%20Preparing%20*VPN*%20deploy%20of%20%3Chttps%3A%2F%2Fcircleci.com%2Fapi%2Fv1.1%2Fproject%2Fgithub%2F${CIRCLE_PROJECT_USERNAME}%2F${CIRCLE_PROJECT_REPONAME}%2F${CIRCLE_BUILD_NUM}%7C${CIRCLE_PROJECT_REPONAME}%20b${CIRCLE_BUILD_NUM}%3E"
      - run:
          name: ORB IPSec - Deploy payload thru docker IPSec tunnel
          command: |
            # start the IPSec tunnel and deploy the bender bot artifacts to the PI
            sudo docker run --cap-add=NET_ADMIN -v /tmp:/tmp \
              danackerson/vpn_deploy:$IPSEC_IMG_VERSION <<parameters.deploy-script>>

executors:
  machine-ubuntu:
    machine:
      image: ubuntu-1604:201903-01
