version: 2.1
description: Using IPSec VPN connectivity from Ubuntu, manage deployment thru tunnel.

jobs:
  remote-deploy:
    parameters:
      deploy-script:
        description: path to executable file for deployment
        type: string
        default: deploy_script.sh
    executor: machine-ubuntu
    steps:
      - deploy-docker-vpn:
          deploy-script: <<parameters.deploy-script>>

commands:
  deploy-docker-vpn:
    parameters:
      deploy-script:
        type: string
    description: Install & configure IPSec VPN
    steps:
      - run:
          name: ORB IPSec - Finalize deploy script
          command: |
            echo -e "#!/bin/bash\n/usr/sbin/vpnc tunnel\n$(cat <<parameters.deploy-script>>)" \
              > <<parameters.deploy-script>>
            echo "/usr/sbin/vpnc-disconnect" >> <<parameters.deploy-script>>
      - run:
          name: ORB IPSec - Setup VPNC IPSec tunnel inside docker container
          command: |
            # just increment this to rebuild image (e.g. on update of $CTX vars)
            IPSEC_IMG_VERSION=v1

            docker login -u $CTX_DOCKER_USER -p $CTX_DOCKER_PASS
            if curl --silent -f -lSL https://hub.docker.com/v2/repositories/danackerson/vpn_deploy/tags/$IPSEC_IMG_VERSION; then
              docker pull danackerson/vpn_deploy:$IPSEC_IMG_VERSION
            else
              cat \<<EOF >tunnel.conf
              IPSec gateway "$CTX_VPNC_GATEWAY"
              IPSec ID "$CTX_VPNC_ID"
              IPSec secret "$CTX_VPNC_SECRET"
              Xauth username "$CTX_VPNC_XAUTH_USERNAME"
              Xauth password "$CTX_VPNC_XAUTH_PASSWD"
              EOF

              curl -O https://raw.githubusercontent.com/danackerson/circleci-orb-ipsec/master/Dockerfile
              # build docker image which will create the IPSec tunnel
              docker build . \
              --build-arg DEPLOY_SCRIPT_FILENAME=<<parameters.deploy-script>> \
              --build-arg SERVER_DEPLOY_KEY=$CTX_SERVER_DEPLOY_SECRET -t vpn_deploy:$IPSEC_IMG_VERSION

              docker push danackerson/vpn_deploy:$IPSEC_IMG_VERSION
            fi
      - run:
          name: ORB IPSec - notify bender slackbot of VPN connection
          command: |
            curl -s -X POST \
            "https://slack.com/api/chat.postMessage?token=$CTX_SLACK_API_TOKEN&channel=$CTX_SLACK_CHANNEL&text=%3Acircleci%3A%20Preparing%20*VPN*%20deploy%20of%20%3Chttps%3A%2F%2Fcircleci.com%2Fapi%2Fv1.1%2Fproject%2Fgithub%2F${CIRCLE_PROJECT_USERNAME}%2F${CIRCLE_PROJECT_REPONAME}%2F${CIRCLE_BUILD_NUM}%7C${CIRCLE_PROJECT_REPONAME}%20b${CIRCLE_BUILD_NUM}%3E"

      - run:
          name: ORB IPSec - Deploy payload thru docker IPSec tunnel
          command: |
            # start the IPSec tunnel and deploy the bender bot artifacts to the PI
            sudo docker run --cap-add=NET_ADMIN --device=/dev/net/tun \
              -v /tmp:/tmp -v /mnt:/mnt vpn_deploy:$IPSEC_IMG_VERSION ./deploy_script.sh

executors:
  machine-ubuntu:
    machine:
      image: ubuntu-1604:201903-01
